Added credentials for GitHub Resolver
python-wheel-build/fromager pull request #128
Opened 2024-07-03 16:56 UTC by shubhbapna

fixes #118 

If `GITHUB_TOKEN` is defined in the current environment then use it to create an authenticated instance of GitHub client and then use it in the resolver.

2024-07-03 17:54 UTC, tiran requested changes
Good work!

Could you please also update `customization.md` and mention the env var there? Thanks!

2024-07-03 18:13 UTC, dhellmann commented
> Good work!
> 
> Could you please also update `customization.md` and mention the env var there? Thanks!

There's an authentication section in the REAMDE. That might be a better spot for docs.

2024-07-03 18:22 UTC, shubhbapna commented
> > Good work!
> > Could you please also update `customization.md` and mention the env var there? Thanks!
> 
> There's an authentication section in the REAMDE. That might be a better spot for docs.

Sorry I don't see an authentication section in the README

2024-07-03 18:29 UTC, dhellmann commented
> > > Good work!
> > > Could you please also update `customization.md` and mention the env var there? Thanks!
> > 
> > 
> > There's an authentication section in the REAMDE. That might be a better spot for docs.
> 
> Sorry I don't see an authentication section in the README

D'oh, that PR didn't merge, yet, sorry. https://github.com/python-wheel-build/fromager/pull/108

2024-07-03 18:57 UTC, shubhbapna commented
I wasn't sure if adding documentation for this would be right in `Using private registries` so I created another section which specifically states why a github token might be needed and how to pass it in `Determining versions via GitHub tags`

Let me know if that works @dhellmann @tiran

2024-07-03 19:03 UTC, dhellmann reviewed
That looks good to me, thank you!

I'll leave this open for @tiran to re-review, since he had asked for changes.

2024-07-05 08:36 UTC, tiran approved these changes

2024-07-05 12:52 UTC, dhellmann approved these changes

2024-07-05 12:53 UTC, merged