raise setuptools minimum version and remove cap
python-wheel-build/fromager pull request #422
Opened 2024-09-16 12:46 UTC by dhellmann

The setuptools issue introduced in 72.0.0 has been fixed in later
releases, so move our minimum past the bad release series and remove the
cap to allow newer versions.

2024-09-16 12:57 UTC, shubhbapna requested changes
We should also remove the setuptools constraint from the e2e test https://github.com/python-wheel-build/fromager/blob/main/e2e/constraints.txt

2024-09-16 14:55 UTC, dhellmann commented
> We should also remove the setuptools constraint from the e2e test https://github.com/python-wheel-build/fromager/blob/main/e2e/constraints.txt

Done

2024-09-16 17:09 UTC, dhellmann commented on e2e/constraints.txt
I thought about that and decided to leave it in place to make it easier to add a constraint later if we need one. I could add a comment to that effect? Unless you think it's better to just remove it entirely.

2024-09-16 17:32 UTC, shubhbapna commented on e2e/constraints.txt
comment works as well

2024-09-16 18:02 UTC, dhellmann commented on e2e/constraints.txt
Done

2024-09-17 00:30 UTC, shubhbapna approved these changes

2024-09-17 00:31 UTC, merged