Cleanup: remove unused arguments from default functions
python-wheel-build/fromager pull request #517
Opened 2024-11-26 14:31 UTC by rd4398

Fixes: https://github.com/python-wheel-build/fromager/issues/483

2024-11-26 14:38 UTC, shubhbapna commented
I just remembered that it will break our documentation since i think it depends on the default functions to generate the docs for the plugin. Is there a workaround for that?

2024-11-26 14:43 UTC, shubhbapna requested changes
I just remembered that it will break our documentation since i think it depends on the default functions to generate the docs for the plugin. Is there a workaround for that?

2024-11-27 08:43 UTC, tiran commented
We not only use the arguments in our docs. They are also used in downstream to compare signatures between default hooks and the plugin hooks.

IMO there is nothing to fix here. It is totally okay to pass additional args to a function if that's part of the API.

2024-12-02 16:19 UTC, shubhbapna commented
> They are also used in downstream to compare signatures between default hooks and the plugin hooks.

I don't think we should enforce that anymore or at the very least change the logic of how we are enforcing that. In fromager we are using a special [invoke function](https://github.com/python-wheel-build/fromager/blob/main/src/fromager/overrides.py#L62) to ensure that a function only receives the arguments it needs. 

So downstream we will need to ensure that the arguments we are passing in our downstream overrides are a subset of all the possible arguments that can be passed. We don't need strict check of signatures.

 
> It is totally okay to pass additional args to a function if that's part of the API.

IMO it adds technical debt and can make it confusing for initial contributors

2024-12-02 17:39 UTC, tiran commented
In my humble opinion, our special invoke function is not a good design. It's not how typical Python APIs are designed. In a typical Python API, it is the responsibility of the callee to deal with unnecessary arguments, e.g. with `**kwargs`.

2024-12-02 21:02 UTC, dhellmann commented
> In my humble opinion, our special invoke function is not a good design. It's not how typical Python APIs are designed. In a typical Python API, it is the responsibility of the callee to deal with unnecessary arguments, e.g. with `**kwargs`.

Yeah, it was a hack to try to avoid introducing breaking changes into the downstream repo when we bumped fromager. It's not an ideal solution, and we should fix that downstream code to use `**kwds`. 

How will we record the formal API of each plugin and then document it if we remove unused arguments from the default functions? Let's figure that out, and then see what that tells us about next steps.

2025-01-23 18:35 UTC, closed without merging